### ISSUE TITLE
Anylogic version

### ISSUE THREAD

**Issue by CloudyDay24** [t-wolfeadam/AnyLogic-Pypeline#1]
Hi!

Great work! 
I have a full license Anylogic University 8.4.0. While loading the library I got the following message "This model was created with newer version of Anylogic. ALP file version: (8.5.1) Upgrade Anylogic to the latest version to open this model."
![image](https://user-images.githubusercontent.com/49958526/87561870-90e0ed80-c6bd-11ea-8f7f-bd3f3f8ad7ca.png)

I changed already the version number within the code of the .alp file "Pypeline Library.alp". With this modification, I can open the file in 8.4. But the same error occurs when loading the .jar file.
Do you know how to insert the library for Anylogic University version 8.4.0?

Update: Same message when inserting the library in Anylogic 8.5.1 PLE.

Thanks a lot!
Jop

**Comment by CloudyDay24** [comment]
So I found something to load the library. 
I opened the .jar file and changed in the library.XML file the version number to mine. This resulted in a proper load-in of the library in Analogic. 
However, I got the following error message when starting the simulation:
![image](https://user-images.githubusercontent.com/49958526/87651665-79544400-c753-11ea-98d7-043dd438e7a6.png)
![image](https://user-images.githubusercontent.com/49958526/87651706-85d89c80-c753-11ea-8ffd-7f77c7c1eccb.png)

Do you know something where it goes wrong?
Thanks!

**Comment by t-wolfeadam** [comment]
> ![image](https://user-images.githubusercontent.com/49958526/87651706-85d89c80-c753-11ea-8ffd-7f77c7c1eccb.png)
> 
> Do you know something where it goes wrong?

Fudging the versions in the files is harmless until something changes in the core of AL...which is the case here :/ 
This error specifically indicates that it cannot create the model because it doesn't know what the "Level" class is - this is something introduced in AL 8.5.

I would first see if you can open the Pypeline alp file inside 8.4. If you can, try saving it as a new model. Doing so will (most likely) clear any use of the Level tag from the XML. If that doesn't work, then you would need to do one of two things:

1. Rework the XML so that it follows a format similar to how models were structured pre-AL 8.5
2. Recreate the library in your current version of AL (8.4) -- recommended (as it's the more stable approach)

After doing whatever method works, you should then export the library (from 8.4) and add that jar to your palette.
