### ISSUE TITLE
Use Pypeline in Anylogic version 8.5

### ISSUE THREAD

**Issue by touchtop** [t-wolfeadam/AnyLogic-Pypeline#12]
In Q&A pdf file, it says "Regarding versions, the latest version of Pypeline (v1.4.0) is built for AnyLogic version 8.6. There’s nothing specific to the logic about v8.6 though, so with minimal modifications, you can adapt Pypeline to any version of AnyLogic." , but hwo to make these "minimal modifications" to use powerful Pypeline in version 8.5? 
thanks a lot.

**Comment by touchtop** [comment]
done,close issue.

**Comment by t-wolfeadam** [comment]
I'm not sure specifically what you (@touchtop) did, but in case others are curious: you'll need to manually edit the Pypeline source model and replace the "AnyLogicWorkspace" tag (near the start of the file) with one from a model saved in your preferred version. Then, open the Pypeline library model in your version of AL and make sure it compiles correctly. If it does, you can export it and add it to your environment.

Necessary disclaimer: This is a workaround for the fact that AnyLogic tends to not let you open models saved in future versions. This is intentional because the way the XML - which AL models are saved as - is generated changes over major versions. However, because Pypeline only uses Java objects, this method _should_ work.

**Comment by touchtop** [comment]
@t-wolfeadam  yes, I just did what you said, and I found that directly modify the library.xml in the jar file also could deal the issue.
Thanks your great work again,  It opened up many possibilities !

**Comment by t-wolfeadam** [comment]
Interesting, I didn't think of that 🤔 ! That may be an easier workaround, thanks for mentioning!
