### ISSUE TITLE
Reinforcement learning

### ISSUE THREAD

**Issue by doncha88** [t-wolfeadam/AnyLogic-Pypeline#14]
Can you please tell me if there will be a version for training with reinforcement learning for python? And when will it be if it will be?

**Comment by t-wolfeadam** [comment]
Hi, there is something similar that you are referring to that is in the prototyping stage at the moment. There's no dedicated time of release, though possibly towards the end of Q2 or Q3 of this year. I'll be updating the readme for this project when a more concrete timeline is in place.

For now, you can always use [Bonsai](https://www.anylogic.com/features/artificial-intelligence/microsoft-bonsai) or [Pathmind](https://www.anylogic.com/features/artificial-intelligence/pathmind).

**Comment by t-wolfeadam** [comment]
(To further clarify, this will be its own separate project, as RL training is not possible with Pypeline)

**Comment by doncha88** [comment]
Thanks for the information. Yes, I looked at these libraries, DL4J is also common now for reinforcement learning, but they are not in python, because of this the problem (. Are there any methods that can force the pypeline to bypass the prohibitions and do reinforcement learning? maybe have some kind of life hack

**Comment by t-wolfeadam** [comment]
There's nothing inherent that restricts you from trying to do RL training using Pypeline. I summarized why this is infeasible below, but for it explained verbally, [see here](https://www.youtube.com/watch?v=rxHD5MuDUvs&t=3170s), and for an explanation with more visuals, see the last two questions of [this Q&A](https://www.anylogic.com/upload/pdf/q-and-a-with-writeups.pdf).

In short, the problem is that with Pypeline, AnyLogic the parent process of Python. If you close the simulation model, the Python connection dies with it - just like if you're running Python in a command prompt and then you close the window. 
With RL, AnyLogic is _also_ the environment for the learning agent. You could start an RL training, but it would only last one episode. Once the AI agent wants to reset the environment, it will also close the Python connection (because it's ending the simulation model). 
The only way around this would be to save the state of the AI at the end of each sim run and resume it at the start of each sim run (But that would be **horribly** inefficient given). The only other way is to host your AI agent as a web app of sorts and communicate with it via HTTP requests (or similar).

**Comment by doncha88** [comment]
thanks for the detailed answer
