### ISSUE TITLE
Python files missing

### ISSUE THREAD

**Issue by DiederikHuijsman** [t-wolfeadam/AnyLogic-Pypeline#26]
Hey Tyler,

Thanks a lot for reacting on my youtube comment. The new updated examples have really helped me get going.

An issue however with the updated pypeline 1.7.0 is that some of the examples are missing the needed python files to observe how they work. Namely the Demo - Agents and Populations with JSON.

**Comment by t-wolfeadam** [comment]
Glad to help and to hear that 🙂 Also, thanks for letting me know about that; I just pushed the missing file, so that should now work!

For convenience, here's the file directly so you don't need to redownload the repo (just needs to be unzipped) - [agent_generator.py.zip](https://github.com/t-wolfeadam/AnyLogic-Pypeline/files/8316425/agent_generator.py.zip)
