### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rsalaza4** [t-wolfeadam/AnyLogic-Pypeline#4]
Hello.

While following your tutorial on installing Pypeline, I got the following error: 

java.io.FileNotFoundException: C:\Program Files\AnyLogic 8.6 Professional\pypeline.properties (Access is denied)

Do you know how to get access? In addition, how where can I get the pypeline.properties file?

Thanks in advance for your help.

Regards,
Roberto

**Comment by t-wolfeadam** [comment]
Hi Roberto,
The properties file is automatically generated next to where you put the pypeline library jar file, which is [poorly] assumed to have write-access (with no extra permissions needed, which the Program Files directory does). I'll push an update shortly with a fix to handle the error. 

If you want to use the properties feature though, you'll need to put the library jar in a folder with write-access (e.g., somewhere in your user folder) or enable write access in that folder -- I recommend the former

**Comment by t-wolfeadam** [comment]
The error is now handled and instead prints out a warning to the console (instead of a full stacktrace). I'll include this in the next official release, but for now you can download it directly here: [Pypeline.jar](https://github.com/t-wolfeadam/AnyLogic-Pypeline/blob/master/Export/Pypeline.jar) - download button is in the middle right.

Closing for now, but let me know if you have other issues about this and I'll re-open it.
